### ISSUE TITLE
Enable test coverage reporting to Code Climate in GH

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/antex#45]
For reference, here is the old TravisCI configuration:

```yaml
env:
  global:
    - CC_TEST_REPORTER_ID=072f27048cd818ab695de7b632d607a6275a8dbebea03fd155fa7de0362be129
language: ruby
rvm:
  - 2.3
  - 2.4
install:
  - source travis/texlive/install
  - bundle install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
  - master
```
